### PR TITLE
[Documentation][BIDS converter] Add instruction for updating datasheet

### PR DESCRIPTION
**Pull request by ycAbout**
improve documentation.

cc

@gdevenyi

### CODE REVIEW

**Comment by gdevenyi** [comment]
Hi @ycAbout this is a good start.

Here's a few things I'd like clearly documented
1. What does each column in the file mean
2. What happens when entries are left blank
3. What are the values are valid for the columns (refer to BIDS spec in appropriate places)

Essentially, we want to write down all that we've learned from poking at the code and reading the spec.

**Comment by ycAbout** [comment]
Hi @gdevenyi , According to your thoughts, I have added more details to this PR. Some of the details are still not clear enough to me, as I'm on the road of learning everything, but this should be good for now and we can always add more later. Please let me know what do you think.

**Comment by gdevenyi** [comment]
This is improving, but I think its still missing some things. The purpose of the documentation is to describe what the columns are for, and why you may want to add something there, we should also provide a hyperlink reference to the BIDS spec fully describing that component. Similarly, the allowed values should say if its a number or a string, for example, and if the exact value is limited to specific strings based on the spec.

**Comment by ycAbout** [comment]
Hi @gdevenyi , 
I totally agree with you. But it will take time to figure out the details. Here is my thoughts. I think we should put more of our time on the code side at the current stage. In this case, we can produce a working solution sooner. On the other hand, even if we have the most perfect doc, brkraw can still not generate the desired output, slowing down our progress. Also, if we later change the code, we may have to change the doc.
Just my opinion, I could be wrong. I will be happy to work with you on the doc side if you still think improve doc has higher priority than improving code at the current stage. Please let me know.

**Pull request merged**
